;;; riii-core.el --- Core editor settings -*- lexical-binding: t; -*-

(require 'autorevert)
(require 'project)
(require 'recentf)
(require 'savehist)
(require 'saveplace)

(defconst riii-state-directory
  (locate-user-emacs-file "var/")
  "Directory for state generated by Emacs.")

(make-directory riii-state-directory t)

;; Keep generated state separate from the configuration source.
(setq custom-file (expand-file-name "custom.el" riii-state-directory)
      savehist-file (expand-file-name "history" riii-state-directory)
      save-place-file (expand-file-name "places" riii-state-directory)
      recentf-save-file (expand-file-name "recentf" riii-state-directory)
      project-list-file (expand-file-name "projects" riii-state-directory)
      global-auto-revert-non-file-buffers t
      tab-always-indent 'complete
      completion-cycle-threshold 3
      read-extended-command-predicate
      #'command-completion-default-include-p)

(setq-default indent-tabs-mode nil)

(load custom-file t)
(savehist-mode 1)
(save-place-mode 1)
(recentf-mode 1)
(global-auto-revert-mode 1)

(provide 'riii-core)
;;; riii-core.el ends here
